# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: chmod -R a+x scripts
      displayName: before_script

    - bash: echo Branch Name is $(Build.SourceBranchName)
      displayName: Branch Name 

    - bash: ./scripts/dotnet-build.sh
      displayName: run_build_script

    - bash: ./scripts/dotnet-test.sh
      displayName: run_test_script

    - bash: ./scripts/dotnet-publish.sh
      displayName: run_publish_script

    - bash: ./scripts/docker-publish-pipelines-azure-devops.sh
      displayName: run_docker-publish-pipelines-azure-devops_script

    - bash: ./scripts/after-success.sh
      displayName: run_after-success_script