name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Moving build to artifacts directory
      run: |
       sh ./scripts/dotnet-build.sh
       sh ./scripts/dotnet-test.sh
       sh ./scripts/dotnet-publish.sh
       sh ./scripts/docker-publish-travis.sh
       sh ./scripts/after-success.sh
       
       
       
       
    
